### ISSUE TITLE
Adding Global Datatype Throws Interface error

### ISSUE THREAD

**Issue by JesseLisby** [Orckestra/C1-CMS-Foundation#453]
I picked up an existing C1 project running version 4.3.5. I had a previous error with just building the project until realizing they were using the wrong dll (4.1).

Now when I try to add a new Global Datatype via the admin screen, I get the following compilation error:
```

20170607 13:55:45.5752 3 571 Error CodeGenerationManager  Compile error: CS0535(4166): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IDynamicTypeFormDefinitionFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FolderPath'
20170607 13:55:45.5757 3 571 Error CodeGenerationManager  Compile error: CS0535(4166): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IDynamicTypeFormDefinitionFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FileName'
20170607 13:55:45.5757 3 571 Error CodeGenerationManager  Compile error: CS0535(11323): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IXsltFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FolderPath'
20170607 13:55:45.5757 3 571 Error CodeGenerationManager  Compile error: CS0535(11323): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IXsltFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FileName'
20170607 13:55:45.5782 3 571 Critical GlobalInitializerFacade  System.InvalidOperationException: Compile error: CS0535(4166): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IDynamicTypeFormDefinitionFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FolderPath'
Compile error: CS0535(4166): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IDynamicTypeFormDefinitionFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FileName'
Compile error: CS0535(11323): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IXsltFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FolderPath'
Compile error: CS0535(11323): 'CompositeGenerated.DataWrappers.Composite_Data_Types_IXsltFileWrapper' does not implement interface member 'Composite.Data.Types.IFile.FileName'

   at Composite.Core.Types.CodeGenerationManager.Compile(CodeGenerationBuilder builder)
   at Composite.Core.Types.CodeGenerationManager.GenerateCompositeGeneratedAssembly(Boolean forceGeneration)
   at Composite.GlobalInitializerFacade.DoInitialize()
   at Composite.GlobalInitializerFacade.InitializeTheSystem()
```

**Comment by JesseLisby** [comment]
When refreshing the project, the datatype seems to be there, but then when I try to update it, it gives me the following error:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Error executing workflow 733e9933-a67f-41cc-b52f-2b1ac114d7a0
  Source=Composite
  StackTrace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId)
   at Composite.C1Console.Workflow.WorkflowFlowController.OnSave(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, FlowControllerServicesContainer formServicesContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.<>c__DisplayClass3.<Render>b__0(Object sender, EventArgs e)
   at Composite_Forms_DocumentExecutionContainer.OnMessage() in c:\SelectQuoteAuto\selectquoteautoandhome\Composite\controls\FormsControls\FormUiContainerTemplates\DocumentExecutionContainer.ascx.cs:line 75
```

**Comment by napernik** [comment]
HI Jesse

You can try removing /bin/Composite.Generated.dll and restarting the site.

**Comment by mawtex** [comment]
Closing due to inactivity
