### ISSUE TITLE
The store named 'administrated' is not supported for data type 'Composite.Data.Types.IPage'

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS-Foundation#466]
C1 CMS: Build no. 6.1.6325.31805

Bare bones install. Created Template, Page Type.. creating new Page - error:  

`InvalidOperationException:
Error executing workflow 8e8fd597-ff31-4ce1-b62d-8c215789442a
Stack trace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId)
   at Composite.C1Console.Workflow.WorkflowFlowController.OnFinish(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, FlowControllerServicesContainer formServicesContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.<>c__DisplayClass0_1.<Render>b__0(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
InvalidOperationException:
The store named 'administrated' is not supported for data type 'Composite.Data.Types.IPage'
Stack trace:
   at Composite.Verify.ThrowInvalidOperationException(String message, Object[] formatArguments)
   at Composite.Plugins.Data.DataProviders.XmlDataProvider.XmlDataTypeStore.GetDataScope(DataScopeIdentifier dataScope, CultureInfo culture, Type type)
   at Composite.Plugins.Data.DataProviders.XmlDataProvider.XmlDataProvider.AddNew[T](IEnumerable`1 dataset)
   at Composite.Data.Foundation.PluginFacades.DataProviderPluginFacade.SyncronizedCall[TProvider,TResult](String providerName, SyncronizedCallDelegate`2 func)
   at Composite.Data.Foundation.PluginFacades.DataProviderPluginFacade.AddNew[T](String providerName, IEnumerable`1 dataset)
   at Composite.Data.DataFacadeImpl.AddNew_AddingMethod[T](String providerName, IEnumerable`1 dataset, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation)
   at Composite.Data.DataFacadeImpl.AddNew[T](IEnumerable`1 datas, Boolean al
Generated 2017-07-27 09:54`

**Comment by aeont** [comment]
`                <Stores>
                    <add dataScope="public" cultureName="en-US" filename="Composite.Data.Types.IPage_en-US.xml"
                        elementName="PageElements" />
                    <add dataScope="administrated" cultureName="en-US" filename="Composite.Data.Types.IPage_Unpublished_en-US.xml"
                        elementName="PageElements" />
                </Stores>`

for some reason this was not created at bare bone install.

**Comment by mawtex** [comment]
Can't repro on clean install.
