### ISSUE TITLE
Workflow error when saving page the second time within the same workflow

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#480]
On a Composite C1 installation im experiencing the following errors when

 1. Editing a page
 2. Pressing save
 3. Making a new edit
 4. Pressing save again

If i close the edit-page and reopen it again i can make the first edit, but not the second.

```
System.Workflow.Activities.EventDeliveryFailedException: Event "Cancel" on interface type "Composite.C1Console.Workflow.IFormsWorkflowEventService" for instance id "a37639e9-02bc-4b4c-8471-e3ee5817267f" cannot be delivered. 
---> System.InvalidOperationException: Workflow with id "a37639e9-02bc-4b4c-8471-e3ee5817267f" not found in state persistence store.    
at System.Workflow.Runtime.WorkflowRuntime.InitializeExecutor(Guid instanceId, CreationContext context, WorkflowExecutor executor, WorkflowInstance workflowInstance)    
at System.Workflow.Runtime.WorkflowRuntime.Load(Guid key, CreationContext context, WorkflowInstance workflowInstance)    
at System.Workflow.Runtime.WorkflowRuntime.GetWorkflow(Guid instanceId)    
at System.Workflow.Activities.ExternalDataExchangeService.EnqueueMessageWrapper.DeliverMessage(ExternalDataEventArgs eventArgs, IComparable queueName, Object message, Object workItem, IPendingWork workHandler)    
at System.Workflow.Activities.WorkflowMessageEventHandler.EventHandler(Object sender, ExternalDataEventArgs eventArgs)    
--- End of inner exception stack trace ---    
at System.Workflow.Activities.WorkflowMessageEventHandler.EventHandler(Object sender, ExternalDataEventArgs eventArgs)    
at Composite.C1Console.Workflow.Foundation.FormsWorkflowEventService.FireCancelEvent(FormEventArgs formEventArgs)    
at Composite.C1Console.Workflow.WorkflowFacadeImpl.FireCancelEvent(Guid instanceId, Dictionary`2 bindings)    
at Composite.C1Console.Workflow.WorkflowFlowController.OnCancel(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer)    
at Composite.Services.FlowControllerServices.CancelFlow(String serializedFlowHandle)

System.InvalidOperationException: Workflow with id "a37639e9-02bc-4b4c-8471-e3ee5817267f" not found in state persistence store.    
at System.Workflow.Runtime.WorkflowRuntime.InitializeExecutor(Guid instanceId, CreationContext context, WorkflowExecutor executor, WorkflowInstance workflowInstance)    
at System.Workflow.Runtime.WorkflowRuntime.Load(Guid key, CreationContext context, WorkflowInstance workflowInstance)    
at System.Workflow.Runtime.WorkflowRuntime.GetWorkflow(Guid instanceId)    
at System.Workflow.Activities.StateMachineWorkflowInstance..ctor(WorkflowRuntime runtime, Guid instanceId)    
at Composite.C1Console.Workflow.WorkflowFacadeImpl.GetCurrentFormEvents(Guid instanceId)    
at Composite.C1Console.Workflow.WorkflowFlowController.AddEventHandles(FormFlowUiDefinition formFlowUiDefinition, Guid instanceId)    
at Composite.C1Console.Workflow.WorkflowFlowController.GetCurrentUiDefinition(FlowToken flowToken)    
at Composite.C1Console.Actions.FlowControllerFacade.GetCurrentUiDefinition(FlowToken flowToken, FlowControllerServicesContainer flowControllerServicesContainer)    
at Composite.Core.WebClient.FlowMediators.WebFlowUiMediator.GetFlowUi(FlowHandle flowHandle, String elementProviderName, String consoleId, String& uiContainerName)
```

**Comment by ThisIsMeJKB** [comment]
I had a client point this exact scenario out to me last week.

Has this been addressed? If not, are we aware of any kind of workaround?

For them, it seems to only be happening on custom/static data types that I have created custom Workflows for. So what I've done is just added the "RerenderView()" function to call to the end of the Save activity so that the add/edit screen will close automatically when the data is saved.

Not ideal but it's currently getting the job done.
