### ISSUE TITLE
Console doesn't work if ~/bin/Composite.Generated.dll is missing

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#507]
Repro:
1) Stop the application pool on IIS
2) Delete /bin/Composite.Generated.dll
3) Start the application pool on IIS
4) Open the console
Expected: Console is opened and working
Actual: There's a message box with the following exception text:

```
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'CompositeGenerated.DynamicSqlDataProvider.Composite_Data_Types_IPageDataId, 8c6a1ba3-7e55-4636-ae5f-50bb591899c7'. Path 'DataId.$type', line 1, position 133. ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly '8c6a1ba3-7e55-4636-ae5f-50bb591899c7'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Composite.Core.Serialization.CompositeJsonSerializer.Deserialize[T](String str)
   at Composite.Data.DataSourceId.Deserialize(String serializedDataSourceId, DataSourceId& dataSourceId, Boolean throwException)
   at Composite.Data.DataSourceId.Deserialize(String serializedDataSourceId)
   at Composite.Data.DataEntityToken.get_DataSourceId()
   at Composite.Data.DataEntityToken.get_Type()
   at Composite.C1Console.Security.EntityToken.ValidateEntityToken()
   at Composite.C1Console.Security.EntityToken.GetHashCode()
   at Composite.C1Console.Security.EntityTokenCacheFacade.CacheKey.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Composite.C1Console.Security.EntityTokenCacheFacade.GetCachedNativeParents(EntityToken entityToken, IEnumerable`1& parentEntityTokens, String userName)
   at Composite.C1Console.Security.RelationshipGraph.ExpandNextLevel(String userName)
   at Composite.C1Console.Security.RelationshipGraph..ctor(EntityToken sourceEntityToken, RelationshipGraphSearchOption searchOption, Boolean lazyEvaluation, Boolean excludeReoccuringNodes)
   at Composite.C1Console.Security.RelationshipGraph..ctor(EntityToken sourceEntityToken, RelationshipGraphSearchOption searchOption, Boolean lazyEvaluation)
   at Composite.C1Console.Security.ParentsFacade.GetAllParents(EntityToken entityToken, Int32 levelCount)
   at Composite.C1Console.Security.ParentsFacade.GetAllParents(EntityToken entityToken)
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.<GetAncestorChains>d__14.MoveNext()
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.<GetAncestorChains>d__13.MoveNext()
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.FindEntityToken(EntityToken ancestorEntityToken, EntityToken entityToken, List`1 nodesToRefresh)
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.FindEntityToken(String serializedAncestorEntityToken, String serializedEntityToken, List`1 openedNodes)
   at Composite.Services.TreeServices.FindEntityToken(String rootEntityToken, String entityToken, List`1 openedNodes) in C:\Sources\GitHub\C1\Website\Composite\services\Tree\TreeServices.asmx:line 240
   --- End of inner exception stack trace ---
```

**Comment by burningice2866** [comment]
Does this happen for all installations or only if have one or more dynamic types registered?

**Comment by napernik** [comment]
All installations. The bug doesn't appear often as we ship with the dll to begin with, and is mostly a problem when there're an error in types meta data and the Composite.Generated.dll cannot be updated, and a developer would try to delete the DLL to get it updated, or move data to another data provider.

**Comment by burningice2866** [comment]
Do you have an idea of when the bug was introduced?

It's a common step in the deploy-process of several sites I'm in involved in to delete Composite.Generated.dll to force C1 to make a new one.

**Comment by napernik** [comment]
Likely only C1 6.2, as that's the version where we've started using JSON serialization for entity tokens.

**Comment by ai-fwd** [comment]
@napernik I cherry-picked this into my repo to solve the problem i was facing (being able to delete Composite.Generated.dll) via an MSBuild AfterBuild Target which was required when switching between DataProviders since the Composite.Generated.dll was stuck pointing to the old DataProvider. 

However, i'm at a bit of a loss because for the life of me i'm not sure where it's creating the new Composite.Generated.dll. It's just not there and any dynamic types (i.e. Community.Blog.*) are failing. 

Here's the output:

> AttributeBasedApplicationStartupHandler : System.IO.FileNotFoundException: Could not load file or assembly 'Composite.Generated, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Composite.Generated, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
=== Pre-bind state information ===
LOG: DisplayName = Composite.Generated, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
LOG: Attempting download of new URL file:///C:/Users/me/AppData/Local/Temp/Temporary ASP.NET Files/vs/c9fa235a/b210ff76/Composite.Generated.DLL.
LOG: Attempting download of new URL file:///C:/Users/me/AppData/Local/Temp/Temporary ASP.NET Files/vs/c9fa235a/b210ff76/Composite.Generated/Composite.Generated.DLL.
LOG: Attempting download of new URL file:///C:/Repos/frontend/Website/C1/Website/bin/Composite.Generated.DLL.
LOG: Attempting download of new URL file:///C:/Repos/frontend/Website/C1/Website/bin/Composite.Generated/Composite.Generated.DLL.
LOG: Attempting download of new URL file:///C:/Users/me/AppData/Local/Temp/Temporary ASP.NET Files/vs/c9fa235a/b210ff76/Composite.Generated.EXE.
LOG: Attempting download of new URL file:///C:/Users/me/AppData/Local/Temp/Temporary ASP.NET Files/vs/c9fa235a/b210ff76/Composite.Generated/Composite.Generated.EXE.
LOG: Attempting download of new URL file:///C:/Repos/frontend/Website/C1/Website/bin/Composite.Generated.EXE.
LOG: Attempting download of new URL file:///C:/Repos/frontend/Website/C1/Website/bin/Composite.Generated/Composite.Generated.EXE.
System.Exception: Failed to load assembly 'Composite.Website, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' 

Seems to be leaning on the cache via:

> CodeGenerationManager : Compile 'DynamicSqlDataProvider : compiling missing classes' in 1718ms
CodeGenerationManager : Types from : C:\Repos\frontend\Website\C1\Website\App_Data\Composite\Cache\Assemblies\f297f1fd-2554-44d1-a645-bd94d0db29e6.dll

Dynamic types missing:

> FileBasedFunctionProvider : System.Web.HttpCompileException (0x80004005): C:\Repos\frontend\Website\C1\Website\App_Data\Razor\Composite\Community\Blog\BlogRenderer.cshtml(132): error CS0246: The type or namespace name 'Entries' could not be found (are you missing a using directive or an assembly reference?)
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp)
   at System.Web.WebPages.BuildManagerWrapper.CreateInstanceOfType[T](String virtualPath)
   at System.Web.WebPages.VirtualPathFactoryManager.CreateInstanceOfType[T](String virtualPath)
   at System.Web.WebPages.WebPageBase.CreateInstanceFromVirtualPath(String virtualPath, IVirtualPathFactory virtualPathFactory)
   at Composite.Plugins.Functions.FunctionProviders.RazorFunctionProvider.RazorFunctionProvider.InstantiateFunction(String virtualPath, String namespace, String name) in C:\Repos\frontend\Website\C1\Composite\Plugins\Functions\FunctionProviders\RazorFunctionProvider\RazorFunctionProvider.cs:line 28
   at Composite.Plugins.Functions.FunctionProviders.FileBasedFunctionProvider.FileBasedFunctionProvider`1.get_Functions() in C:\Repos\frontend\Website\C1\Composite\Plugins\Functions\FunctionProviders\FileBasedFunctionProvider\FileBasedFunctionProvider.cs:line 90
Exception thrown: 'System.Web.HttpCompileException' in System.Web.WebPages.dll
FileBasedFunctionProvider : Error instantiating function Composite.Community.Blog.Latest 

I can confirm that if a Composite.Generated.dll is present and IIS is running and the dll is deleted it does immediately create a new one

**Comment by burningice2866** [comment]
@ai-fwd you cannot delete `Composite.Generated.dll` if anything on your website relies on Dynamic Types. Its a chicken and egg problem. C1 can only create a new `Composite.Generated.dll` when its fully up and running but it can't start if any code on the websites relies on `Composite.Generated.dll` and therien is the dilemma.

If you accidentally remove `Composite.Generated.dll` and can't get C1 to start anymore the simplest workaround is to delete all files you might have in `App_Code` and `App_Data\Razor` and cross your fingers that that will make C1 start, and when a new `Composite.Generated.dll` has been made you can restore the files back again.

**Comment by ai-fwd** [comment]
@burningice2866 doesn't that contradict the repo steps? Step #2 is "Delete /bin/Composite.Generated.dll"

I have a bootstrap Composite.Generated.dll that i use to get it up and running in these situations -- i just thought this bug fix addressed that problem.

@napernik can you confirm this is only for scenarios where there are no dynamic types?

**Comment by burningice2866** [comment]
@ai-fwd no... if you have a pure Static Types site then you can delete the ´Composite.Generated.dll` as often as you'd like and C1 will still be able to start up since all references to types exist as actual interfaces somewhere else that in `Composite.Generated.dll`.

C1 is also able to start up if you have dynamic types in ie. XSLT functions since they are not statically compiled at will therefor not throw the error you're seeing as when C1 tries to load your Razor Functions referencing types that doesn't exist anywhere yet.

IMO the whole thing with C1 being the compiler of Dynamic Types is a good idea but messy implemented causing the whole Chicken and Egg dilemma. Ie. if we just could invoke the Dynamic Types compilation pipeline without having to run the actual website things could be greatly simplified. 

What if we could start the C1 Console in a special Compilation/Recovery-mode, that is, no loading of functions and templates, no loading of StartupHandler, no loading of anything external really except the defined dynamic types and then let C1 compile them into a new `Composite.Generated.dll` which would then allow C1 to start properly.

**Comment by ai-fwd** [comment]
agreed, that would be a nice addition to avoid all this.

**Comment by burningice2866** [comment]
There was a thread on the old Codeplex, almost 5 years old i see, touching the subject of being able to use and invoke parts of C1 without having to run the whole thing https://c1cms.codeplex.com/workitem/1271

That would open up for the possibility to compile all datatypes via ie. an API or command line without having to run all of C1 in the context of a website and all.

I've seen posts on Stackoverflow where people just reference Composite.dll in their own project/Windows application with hopes of being able to query data as long as the folder structure is in place. No luck though since everything is tangled together and requires a lot of Web-specific things to be in place even though neither Compilation of the Data Layer per-se is web-dependent.

**Comment by napernik** [comment]
Hi @burningice2866  

If you have time to play around with it, you can try the following code:

```
using Composite.Core.WebClient;


namespace CompositeGeneratedGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            HttpContext.Current = new HttpContext(new HttpRequest("", "http://www.dr.dk", ""), new HttpResponse(new StringWriter()));
            AppDomain.CurrentDomain.SetData("APPBASE", args[0]);

            ApplicationLevelEventHandlers.Application_Start(null, null);

            SystemSetupFacade.IsSystemFirstTimeInitialized = true;

            CultureInfo locale = new CultureInfo("en-US");

            ApplicationLevelEventHandlers.ApplicationStartInitialize(false);

            LocalizationFacade.AddLocale(locale, "", true, false);
            LocalizationFacade.SetDefaultLocale(locale);
        }
    }
}
```

The way to use it: compile it into a console application, drop into the /Bin folder, and run with passing the website directory folder as a parameter. 

That's what we internally use to generate /bin/Composite.Generated.dll during the build on an empty site, I'm not sure how it would work for a not empty site with multiple packages and multiple dynamic types. Either some modifications may be required, or you may have a copy of the website that would just have the right dlls and meta data files to generate the dll, and only copy the result dll to the original website, to avoid any kind of side effects.

**Comment by napernik** [comment]
> @napernik can you confirm this is only for scenarios where there are no dynamic types?

The bug is there whether or not there're dynamic types. Normally Composite.Generated.dll should appear when the website is stopping. Normally you can start and stop the website to get a new version of the dll. If it doesn't appear - there must be an exception in the log files with the details. The fix won't address the missing file, it is rather ensures that the console is not completely crashing for no reason if it is missing.

**Comment by burningice2866** [comment]
@napernik i know that code but its next to impossible to tweak it for all possible real life installations since its basically just still triggering a full load of C1 including all its StartupHandlers, Function Providers and what not and at in each of those steps there is a chance for some code to rely on a dynamic type which has yet been compiled.

Something like this would be more useful

```
static void Main(string[] args)
{
    AppDomain.CurrentDomain.SetData("APPBASE", args[0]);

    CodeGenerationManager.GenerateCompositeGeneratedAssembly(true);
}
```
