### ISSUE TITLE
No longer able to create pages in a Bacground Task (v6.3)

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#539]
After upgrading to version 6.3 i'm no longer able to create pages via the data layer in a background task.

The exception when calling DataConnection.Add passing a IPage instance is

```
System.InvalidOperationException: Cannot resolve scoped service 'Composite.Search.DocumentSources.IndexUpdateActionContainer' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Composite.Search.DocumentSources.DataChangesIndexNotifier.<Start>b__10_0(Object sender, DataEventArgs args)
   at Composite.Data.DataEventSystemFacade.<>c__DisplayClass50_0.<FireDataAfterAddEvent>b__0(DataEventHandler callback)
   at Composite.Data.DataEventSystemFacade.Fire[DelegateType](Hashtable`2 collection, Type dataType, ExecuteCallback`1 runner)
   at Composite.Data.DataEventSystemFacade.FireDataAfterAddEvent(Type dataType, IData data)
   at Composite.Data.DataEventSystemFacade.FireDataAfterAddEvent[T](IData data)
   at Composite.Data.DataFacadeImpl.AddNew_AddingMethod[T](String providerName, IEnumerable`1 dataset, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation)
   at Composite.Data.DataFacadeImpl.AddNew[T](IEnumerable`1 datas, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation, List`1 writeableProviders)
   at Composite.Data.DataFacade.AddNew[T](IEnumerable`1 collection, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performeValidation, List`1 writeableProviders)
   at Composite.Data.DataFacade.AddNew[T](T data)
   at Composite.Core.Implementation.DataConnectionImplementation.Add[TData](TData item)
   at Composite.Data.DataConnection.Add[TData](TData item)
   at katuaq.EbilletEventSynchronizer.CreatePage(IEvent evt, String descripton, String content, CultureInfo culture) in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq.ebillet\EbilletEventSynchronizer.cs:line 121
   at katuaq.EbilletEventSynchronizer.CreateEventPage(DataConnection data, Guid parentPage, IEvent evt, String description, String content) in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq.ebillet\EbilletEventSynchronizer.cs:line 74
   at katuaq.EbilletEventSynchronizer.SynchronizeImpl(XElement element, DataConnection data) in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq.ebillet\EbilletEventSynchronizer.cs:line 65
   at katuaq.EbilletDataSynchronizer`1.Synchronize() in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq.ebillet\EbilletDataSynchronizer.cs:line 45
   at katuaq.ScheduledTasks.UpdateDataTask.Run(CancellationToken cancellationToken) in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq.ebillet\UpdateDataTask.cs:line 43
   at katuaq.ScheduledTasks.TaskRunner.Run(IJobCancellationToken cancellationToken, String task) in D:\Work\DOT GL\Katuaq\code\assemblies\katuaq\ScheduledTasks\TaskRunner.cs:line 22
```

I've tried wrapping my code in

```
var scopeFactory = ServiceLocator.GetService<IServiceScopeFactory>();
using (scopeFactory.CreateScope())
{
   ...
}
```

but that doesn't help - most likely due to [this method](https://github.com/Orckestra/C1-CMS-Foundation/blob/d93c3f8bbc44dbdf4eaf657a0f426434b0775aa9/Composite/Core/ServiceLocator.cs#L223) which is only able to manage a scope using `HttpContext`.

**Comment by burningice2866** [comment]
As far as i understand it, [ServiceLocator](https://github.com/Orckestra/C1-CMS-Foundation/blob/d93c3f8bbc44dbdf4eaf657a0f426434b0775aa9/Composite/Core/ServiceLocator.cs) needs a method where a Service Scope can be created/disposed using other means that via HttpContext.

**Comment by burningice2866** [comment]
So a hacky workaround is to do this, but seriously?`

```
var scopeFactory = ServiceLocator.GetService<IServiceScopeFactory>();
using (var scope = scopeFactory.CreateScope())
{
    var request = new HttpRequest("", "http://katuaq.gl", "");
    var context = new HttpContext(request, new HttpResponse(new StringWriter()));

    context.Items["HttpApplication.ServiceScope"] = scope;

    HttpContext.Current = context;

    ....
}
```

**Comment by napernik** [comment]
It looks like the scope validation gets enabled when **<compilation debug="true" .. />** is in web.config. The scoped interface is requested by data indexing code, so setting **debug="false"** would remove the exception, but the changes to the pages will not be propagated to the search index. 

One way of addressing it would be to automatically create a scope when DataConnection is created and keep a reference to it in ThreadDataManager, that is initialized there as well.

**Comment by napernik** [comment]
Please check if the latest change addresses the issue you have

**Comment by burningice2866** [comment]
Comments added to the commit

**Comment by burningice2866** [comment]
Most importantly, there still needs a way to explicitly create a new Service Scope since you can have scoped services not related to a DataConnection.
