### ISSUE TITLE
[6.3] Scheduled publishing/unpublishing doesn't work with debug builds of Composite.dll

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#543]
1) Use a debug build of ~/bin/Composite.dll
2) Edit a publishable data item, specify a future publish or unpublish time
3) Wait for the time
Expected: the data is published/unpublished according to the specified time
Actual: the following error appears in the log:

```
System.InvalidOperationException: Cannot resolve scoped service 'Composite.Search.DocumentSources.IndexUpdateActionContainer' from root provider.   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Composite.Core.ServiceLocator.GetService[T]() in C:\Sources\GitHub\C1\Composite\Core\ServiceLocator.cs:line 42
   at Composite.Search.DocumentSources.DataChangesIndexNotifier.GetActionContainer() in C:\Sources\GitHub\C1\Composite\Search\DocumentSources\DataChangesIndexNotifier.cs:line 52
   at Composite.Search.DocumentSources.DataChangesIndexNotifier.<Start>b__10_2(Object sender, DataEventArgs args) in C:\Sources\GitHub\C1\Composite\Search\DocumentSources\DataChangesIndexNotifier.cs:line 42
   at Composite.Data.DataEventSystemFacade.<>c__DisplayClass57_0.<FireDataAfterUpdateEvent>b__0(DataEventHandler callback) in C:\Sources\GitHub\C1\Composite\Data\DataEventSystemFacade.cs:line 522
   at Composite.Data.DataEventSystemFacade.Fire[DelegateType](Hashtable`2 collection, Type dataType, ExecuteCallback`1 runner) in C:\Sources\GitHub\C1\Composite\Data\DataEventSystemFacade.cs:line 154
   at Composite.Data.DataEventSystemFacade.FireDataAfterUpdateEvent(Type dataType, IData data) in C:\Sources\GitHub\C1\Composite\Data\DataEventSystemFacade.cs:line 522
   at Composite.Data.DataFacadeImpl.Update(IEnumerable`1 dataset, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation) in C:\Sources\GitHub\C1\Composite\Data\DataFacadeImpl.cs:line 325
   at Composite.Data.DataFacade.Update(IEnumerable`1 dataset) in C:\Sources\GitHub\C1\Composite\Data\DataFacade.cs:line 854
   at Composite.Data.DataFacade.Update(IData data) in C:\Sources\GitHub\C1\Composite\Data\DataFacade.cs:line 836
   at Composite.C1Console.Scheduling.DataUnpublishSchedulerWorkflow.Execute() in C:\Sources\GitHub\C1\Composite.Workflows\C1Console\Scheduling\DataUnpublishSchedulerWorkflow.cs:line 53
   at Composite.C1Console.Scheduling.BaseSchedulerWorkflow.finalizeCodeActivity_ExecuteCode(Object sender, EventArgs e) in C:\Sources\GitHub\C1\Composite.Workflows\C1Console\Scheduling\BaseSchedulerWorkflow.cs:line 43
   at System.Workflow.ComponentModel.Activity.RaiseEvent(DependencyProperty dependencyEvent, Object sender, EventArgs e)
   at System.Workflow.Activities.CodeActivity.Execute(ActivityExecutionContext executionContext)
   at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
   at System.Workflow.Runtime.Scheduler.Run()
System.InvalidOperationException: Error executing workflow e04be4e1-536d-45dd-910f-ec1be30cae22 
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId) in C:\Sources\GitHub\C1\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 281
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(WorkflowInstance workflowInstance) in C:\Sources\GitHub\C1\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 288
   at Composite.C1Console.Workflow.WorkflowFacade.RunWorkflow(WorkflowInstance workflowInstance) in C:\Sources\GitHub\C1\Composite\C1Console\Workflow\WorkflowFacade.cs:line 148
   at Composite.C1Console.Workflow.WorkflowActionExecutor.Execute(String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Workflow\WorkflowActionExecutor.cs:line 27
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(IActionExecutorSerializedParameters actionExecutor, String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 152
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer, TaskManagerEvent taskManagerEvent) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 79
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 25
   at Composite.C1Console.Actions.Data.ProxyDataActionExecuter.Execute(String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\Data\ProxyDataActionExecuter.cs:line 26
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(IActionExecutorSerializedParameters actionExecutor, String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 152
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer, TaskManagerEvent taskManagerEvent) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 79
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\Sources\GitHub\C1\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 25
   at Composite.Core.WebClient.FlowMediators.ActionExecutionMediator.ExecuteElementAction(ElementHandle elementHandle, ActionHandle actionHandle, String consoleId) in C:\Sources\GitHub\C1\Composite\Core\WebClient\FlowMediators\ActionExecutionMediator.cs:line 19
   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.ExecuteElementAction(String providerName, String serializedEntityToken, String piggybag, String serializedActionToken, String consoleId) in C:\Sources\GitHub\C1\Composite\Core\WebClient\FlowMediators\TreeServicesFacade.cs:line 244
   at Composite.Services.TreeServices.ExecuteSingleElementAction(ClientElement clientElement, String serializedActionToken, String consoleId) in C:\Sources\GitHub\C1\Website\Composite\services\Tree\TreeServices.asmx:line 368
```

**Comment by burningice2866** [comment]
Same root issue as described here https://github.com/Orckestra/C1-CMS-Foundation/issues/539
