### ISSUE TITLE
[Page Types] Duplicate content placeholders are possible

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#586]
**Repro**:

1. Create a page type with defaults
2. Add a content placeholder to it, which exists (e.g. "content" on 'Venus")
3. [optional] Add some content to it
4. Add another content placeholder with the same name as in Step 2
5.  [optional] Add some content to it
6. Try and add a page of this type

**Expected**:

Step 4: The step is not possible. A duplicate placeholder is not allowed

**Actual**:

Step 4: The step is possible. You can add different contents in tow duplicate placeholders
Step 6: A server error pops up (see below)

![chrome_2018-06-25_12-29-15](https://user-images.githubusercontent.com/14821915/41842601-f2093c92-7873-11e8-9945-cde69fecc222.png)

--- SERVER ERROR ---

> InvalidOperationException:
> Error executing workflow 132370b3-9034-4e10-9e61-440f10abd894
> Stack trace:
>    at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId)
>    at Composite.C1Console.Workflow.WorkflowFlowController.OnFinish(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer)
>    at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, FlowControllerServicesContainer formServicesContainer)
>    at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.<>c__DisplayClass0_1.<Render>b__0(Object sender, EventArgs e)
>    at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
>    at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
> ArgumentException:
> dataset
> Parameter name: Key violation error. A data element with the same dataId is already added. Type: Composite.Data.Types.IPagePlaceholderContent
> Stack trace:
>    at Composite.Plugins.Data.DataProviders.XmlDataProvider.XmlDataProvider.AddNew[T](IEnumerable`1 dataset)
>    at Composite.Data.Foundation.PluginFacades.DataProviderPluginFacade.<>c__DisplayClass10_0`1.<AddNew>b__0(IWritableDataProvider provider)
>    at Composite.Data.Foundation.PluginFacades.DataProviderPluginFacade.SyncronizedCall[TProvider,TResult](String providerName, Func`2 func)
>    at Composite.Data.Foundation.PluginFacades.DataProviderPluginFacade.AddNew[T](String providerName, IEnumerable`1 dataset)
>    at Composite.Data.DataFacadeImpl.AddNew_AddingMethod[T](String providerName, IEnumerable`1 dataset, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation)
>    at Composite.Data.DataFacadeImpl.AddNew[T](IEnumerable`1 datas, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation, List`1 wri
> Generated 2018-06-25 12:30

**Comment by wwwysocki** [comment]
Verified on 20180626.2 (dev)
