### ISSUE TITLE
[Tree Definitions] Can't remove a Console app (e.g. Blog) if an auto-attached app is added

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#590]
**Repro**:

1. Use the Venus starter site, or any site that has some Console Application like Blog added via Tree Definitions 
In `~\App_Data\Composite\TreeDefinitions\`, add an XML file (tree defintion) with the XML provided further below
2. In Content, select any page and make sure that the "GUID" button appears in the button bar
3. Right-click the "Blog" page (on "Venus")
4. Select Remove Application

**Expected**:

You can follow through with the application removal

**Actual**:

A server error pops up (see below)

--- TREE DEFINITION XML ---

```
  <ElementStructure xmlns="http://www.composite.net/ns/management/trees/treemarkup/1.0" xmlns:f="http://www.composite.net/ns/function/1.0"> 
    <ElementStructure.AutoAttachments> 
      <DataType Type="Composite.Data.Types.IPage" /> 
    </ElementStructure.AutoAttachments> 
    <ElementRoot> 
      <Actions> 
        <MessageBoxAction Label="GUID" MessageBoxTitle="${C1:Data:Composite.Data.Types.IPage:Title}" MessageBoxMessage="${C1:Data:Composite.Data.Types.IPage:Id}" /> 
      </Actions> 
    </ElementRoot> 
  </ElementStructure>
```

--- SERVER ERROR ---

> NullReferenceException:
> Object reference not set to an instance of an object.
> Stack trace:
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.SelectorTemplateUserControlBase.GetPropertyValue(Object object, String propertyName, Type& lastOptionObjectType, PropertyInfo& lastUsedPropertyInfo)
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.SelectorTemplateUserControlBase.InitializeSelectorElements()
>    at ASP.composite_controls_formscontrols_formuicontroltemplates_selectors_selector_ascx.InitializeViewState()
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.TemplatedSelectorUiControl.InitializeViewState()
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.TemplatedContainerUiControl.InitializeViewState()
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.TemplatedContainerUiControl.InitializeViewState()
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.TemplatedContainerUiControl.InitializeViewState()
>    at Composite.Plugins.Forms.WebChannel.UiControlFactories.WebEmbeddedFor
> Generated 2018-06-25 13:04

**Comment by wwwysocki** [comment]
Verified on 20180626.2 (dev)
