### ISSUE TITLE
[HierarchicalSelector] 'Value cannot be null' exception when used on an optional field

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#597]
**Prepare**:

1. Create a simple global data type with 2+ `String` fields.
2. Make one String field optional (Optional = Yes)
3. Change the widget of this field to "HierarchicalSelector" and...
3. ... set its TreeNodes parameter to the function from [this code sample](https://github.com/Orckestra/C1-CMS-Foundation/commit/ee8721e5bc630f3a5501a41d960a02cd34bc3986#commitcomment-22296208)
4. Save the data type

**Repro**:

1. Add an item of this type

**Expected**:

The data item editor opens

**Actual**:

Server Error:

> ArgumentNullException:
> Value cannot be null.
> Parameter name: source
> Stack trace:
>    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
>    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
>    at ASP.composite_controls_formscontrols_formuicontroltemplates_selectors_hierarchicalselector_ascx.RenderTree(StringBuilder sb, SelectionTreeNode treeNode)
>    at ASP.composite_controls_formscontrols_formuicontroltemplates_selectors_hierarchicalselector_ascx.OnPreRender(EventArgs args)
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRenderRecursiveInternal()
>    at System.Web.UI.Control.PreRender
> Generated 2018-06-27 10:19

**Comment by VolodymyrMuzyka** [comment]
@wwwysocki  @napernik similar noted when using within razor function. 

Fix is simple: add null check in line #55: C:\development\WUBS\WUBS.CompositeC1\Website\Composite\controls\FormsControls\FormUiControlTemplates\Selectors\HierarchicalSelector.ascx    

i.e. if (SelectedKeys.Contains(treeNode.Key))  => if (SelectedKeys != null && SelectedKeys.Contains(treeNode.Key))
