### ISSUE TITLE
CSS don't work at all

### ISSUE THREAD

**Issue by Safety1st** [Orckestra/C1-CMS-Foundation#641]
I installed default 'Open Cph - Razor' starter site and immediately noticed that site is not properly formatted. You could see it [here](http://c1cms.1gb.ru/).

Hosting support provided me error trace:
```Server Error in '/' Application.
Compiling less caused a scripting host error.
fs.js:671
 return binding.stat(pathModule._makeLong(path));
                ^
Error: EPERM, operation not permitted 'd:\web\1gb.ru\hosted'
   at Object.fs.statSync (fs.js:671:18)
   at Object.realpathSync (fs.js:1259:12)
   at tryFile (module.js:137:15)
   at Function.Module._findPath (module.js:176:18)
   at Function.Module._resolveFilename (module.js:329:25)
   at Function.Module._load (module.js:273:25)
   at Function.Module.runMain (module.js:490:10)
   at startup (node.js:123:16)
   at node.js:1027:3
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: Compiling less caused a scripting host error.
fs.js:671
 return binding.stat(pathModule._makeLong(path));
                ^
Error: EPERM, operation not permitted 'd:\web\1gb.ru\hosted'
   at Object.fs.statSync (fs.js:671:18)
   at Object.realpathSync (fs.js:1259:12)
   at tryFile (module.js:137:15)
   at Function.Module._findPath (module.js:176:18)
   at Function.Module._resolveFilename (module.js:329:25)
   at Function.Module._load (module.js:273:25)
   at Function.Module.runMain (module.js:490:10)
   at startup (node.js:123:16)
   at node.js:1027:3


Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[InvalidOperationException: Compiling less caused a scripting host error. 
fs.js:671
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: EPERM, operation not permitted 'd:\web\1gb.ru\hosted'
    at Object.fs.statSync (fs.js:671:18)
    at Object.realpathSync (fs.js:1259:12)
    at tryFile (module.js:137:15)
    at Function.Module._findPath (module.js:176:18)
    at Function.Module._resolveFilename (module.js:329:25)
    at Function.Module._load (module.js:273:25)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:123:16)
    at node.js:1027:3
]
   Orckestra.Web.Css.Less.LessCssCompiler.GetOutput(Process process) +313
   Orckestra.Web.Css.Less.LessCssCompiler.CompileCss(String lessFilePath, String cssFilePath, DateTime folderLastUpdatedUtc) +69
 
Orckestra.Web.Css.Less.CssCompilationHttpModule.context_BeginRequest(HttpCon
text context) +1455
   Orckestra.Web.Css.Less.<>c__DisplayClass7_0.<Init>b__0(Object a, EventArgs b) +70
 
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.
Execute() +141
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously) +71


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.7.3163.0
```

Also the were some comments from technician director that I not being a web master direct to you:

It's trace by accessing `http://c1cms.1gb.ru/Frontend/Styles/style.less` URL. It seems CMS code tries to read directory & file lists from the root to the site directory and obviously get error because on shared hosting not all folders are accessible (here it is `d:\web\1gb.ru\hosted`). It seems wrong action because site shall not program anything outside its home directory and subdirectories.

Please correct this behavior because I really wish to use your CMS but a lot of time just can't find cheep hosting suitable for it.

**Comment by mawtex** [comment]
Thanks for the excellent issue description - this is a known problem we reported with node years ago (even tried with a [PR](https://github.com/napernik/node/commit/d51418e488dfc6c70a277c43ece499fba4fac6f1) but it was rejected).

Very likely the issue has been fixed in node, you can test like this:

1) Download from https://nodejs.org/en/download/ (grab the zip, 32 bit Windows)
2) Copy node.exe from the zip to your web directory ~/Frontend/Orckestra/Web/Css/Less (overwrite existing)
3) Test http://c1cms.1gb.ru/Frontend/Styles/style.less (should return glorious CSS)

We don't have a repro case, so I can't verify if this is a good fix, sorry. If it is a fix, please let us know here, and we will update the node.exe that ship with the [LESS package](https://github.com/Orckestra/CMS-Packages/tree/master/Composite.Web.Css.Less).

A workaround that will for sure work is serving 'done' CSS and skip the LESS compile step on your hosted website, like this:

1) On your local machine or similar, run the website and request ~/Frontend/Styles/style.less
2) Save the file as style.css and add it as a flat file to your website
3) Edit the Razor Function (on the Function perspective) and change the `<link />` pointing to style.less so it points to your CSS

**Comment by Safety1st** [comment]
@mawtex Do I need only node.exe from current 'line' or with some components inside the archive?

**Comment by Safety1st** [comment]
I used node.exe both from 'lts' & 'current' platforms.
LTS:
```Server Error in '/' Application.

Compiling less caused a scripting host error. fs.js:115
   throw err;
   ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
   at Object.realpathSync (fs.js:1454:7)
   at toRealPath (internal/modules/cjs/loader.js:201:13)
   at Function.Module._findPath (internal/modules/cjs/loader.js:267:22)
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:577:25)
   at Function.Module._load (internal/modules/cjs/loader.js:506:25)
   at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
   at startup (internal/bootstrap/node.js:285:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Compiling less caused a scripting host error. fs.js:115
   throw err;
   ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
   at Object.realpathSync (fs.js:1454:7)
   at toRealPath (internal/modules/cjs/loader.js:201:13)
   at Function.Module._findPath (internal/modules/cjs/loader.js:267:22)
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:577:25)
   at Function.Module._load (internal/modules/cjs/loader.js:506:25)
   at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
   at startup (internal/bootstrap/node.js:285:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)


Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace: 


[InvalidOperationException: Compiling less caused a scripting host error. fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
    at Object.realpathSync (fs.js:1454:7)
    at toRealPath (internal/modules/cjs/loader.js:201:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:267:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:577:25)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
]
   Orckestra.Web.Css.Less.LessCssCompiler.GetOutput(Process process) +313
   Orckestra.Web.Css.Less.LessCssCompiler.CompileCss(String lessFilePath, String cssFilePath, DateTime folderLastUpdatedUtc) +71
   Orckestra.Web.Css.Less.CssCompilationHttpModule.context_BeginRequest(HttpContext context) +1455
   Orckestra.Web.Css.Less.<>c__DisplayClass7_0.<Init>b__0(Object a, EventArgs b) +70
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3163.0```

Current:
```Server Error in '/' Application.

Compiling less caused a scripting host error. fs.js:121
   throw err;
   ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
   at Object.realpathSync (fs.js:1479:7)
   at toRealPath (internal/modules/cjs/loader.js:205:13)
   at Function.Module._findPath (internal/modules/cjs/loader.js:287:22)
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:600:25)
   at Function.Module._load (internal/modules/cjs/loader.js:529:25)
   at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
   at executeUserCode (internal/bootstrap/node.js:342:17)
   at startExecution (internal/bootstrap/node.js:276:5)
   at startup (internal/bootstrap/node.js:227:5)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Compiling less caused a scripting host error. fs.js:121
   throw err;
   ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
   at Object.realpathSync (fs.js:1479:7)
   at toRealPath (internal/modules/cjs/loader.js:205:13)
   at Function.Module._findPath (internal/modules/cjs/loader.js:287:22)
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:600:25)
   at Function.Module._load (internal/modules/cjs/loader.js:529:25)
   at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
   at executeUserCode (internal/bootstrap/node.js:342:17)
   at startExecution (internal/bootstrap/node.js:276:5)
   at startup (internal/bootstrap/node.js:227:5)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)


Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace: 


[InvalidOperationException: Compiling less caused a scripting host error. fs.js:121
    throw err;
    ^

Error: EPERM: operation not permitted, lstat 'd:\hst'
    at Object.realpathSync (fs.js:1479:7)
    at toRealPath (internal/modules/cjs/loader.js:205:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:287:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:600:25)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
]
   Orckestra.Web.Css.Less.LessCssCompiler.GetOutput(Process process) +313
   Orckestra.Web.Css.Less.LessCssCompiler.CompileCss(String lessFilePath, String cssFilePath, DateTime folderLastUpdatedUtc) +71
   Orckestra.Web.Css.Less.CssCompilationHttpModule.context_BeginRequest(HttpContext context) +1455
   Orckestra.Web.Css.Less.<>c__DisplayClass7_0.<Init>b__0(Object a, EventArgs b) +70
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3163.0```

What do you see? I intensionally left web.config with `customErrors mode="Off"` in `/Frontend/Orckestra/Web/Css/Less`.

Which repository should I write about the bug: node or LESS?

**Comment by Safety1st** [comment]
Anyway I fond hosting that supports all the features `http://isotonic.ru/` so that problem for me could be ignored :)

**Comment by Safety1st** [comment]
I found hosting that seems to fully support the C1 features. But after switching to SQL site `http://isotonic.ru/` stopped work. Again :)
```

The source code that generated this unhandled exception can only be shown when compiled in debug mode. To enable this, please follow one of the below steps, then request the URL:1. Add a "Debug=true" directive at the top of the file that generated the error. Example:   <%@ Page Language="C#" Debug="true" %>or:2) Add the following section to the configuration file of your application:<configuration>    <system.web>        <compilation debug="true"/>    </system.web></configuration> Note that this second technique will cause all files within a given application to be compiled in debug mode. The first technique will cause only that particular file to be compiled in debug mode.Important: Running applications in debug mode does incur a memory/performance overhead. You should make sure that an application has debugging disabled before deploying into production scenario.

The source code that generated this unhandled exception can only be shown when compiled in debug mode. To enable this, please follow one of the below steps, then request the URL:1. Add a "Debug=true" directive at the top of the file that generated the error. Example:   <%@ Page Language="C#" Debug="true" %>or:2) Add the following section to the configuration file of your application:<configuration>    <system.web>        <compilation debug="true"/>    </system.web></configuration> Note that this second technique will cause all files within a given application to be compiled in debug mode. The first technique will cause only that particular file to be compiled in debug mode.Important: Running applications in debug mode does incur a memory/performance overhead. You should make sure that an application has debugging disabled before deploying into production scenario.
--

[InvalidOperationException: 0 writeable data providers exists for data 'Composite.Data.Types.IUrlConfiguration'.]    Composite.Data.DataFacadeImpl.AddNew(IEnumerable`1 datas, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation, List`1 writeableProviders) +937    Composite.Data.DataFacadeImpl.AddNew(IEnumerable`1 datas, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performValidation, List`1 writeableProviders) +427    Composite.Data.DataFacade.AddNew(IEnumerable`1 collection, Boolean allowStoreCreation, Boolean suppressEventing, Boolean performForeignKeyIntegrityCheck, Boolean performeValidation, List`1 writeableProviders) +95    Composite.Data.DataFacade.AddNew(T data) +154    Composite.Core.Routing.HostnameBindingsFacade.Initialize() +246    Composite.Core.WebClient.ApplicationLevelEventHandlers.ApplicationStartInitialize(Boolean displayDebugInfo) +321    Composite.Core.WebClient.ApplicationLevelEventHandlers.Application_Start(Object sender, EventArgs e) +234    ASP.global_asax.Application_Start(Object sender, EventArgs e) +32  [HttpException (0x80004005): 0 writeable data providers exists for data 'Composite.Data.Types.IUrlConfiguration'.]    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +10093481    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +218    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296  [HttpException (0x80004005): 0 writeable data providers exists for data 'Composite.Data.Types.IUrlConfiguration'.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10074680    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
--
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3163.0 
```

--

**Comment by mawtex** [comment]
For the node exception, the problem lies with node (not LESS). For some reason node will crawl the directory tree from the root up, and fail if it doesn't have permissions on the way.

From the error message on your website after moving to SQL (0 writeable data providers exists for data 'Composite.Data.Types.IUrlConfiguration') it seems the migration from XML to SQL failed. Likely there will be error details in ~/App_Data/Composite/Logfiles which can shed light on this. I would restore the original XML based website no matter what, and then proceed based on the error details found in the log.

**Comment by Safety1st** [comment]
First time I used symbol `&` in password that was eventually escaped as `&amp`. I correted connection string in `Web.config` but there was too late.

Now I recreated the enviroment from scrarch and started converting. Cosole all the time show indicator with 'Working... Please wait.', database is about 80MB and `~/App_Data/Composite/Logfile` is clean. Could you help me again?

**Comment by Safety1st** [comment]
First time I used symbol `&` in password that was eventually escaped as `&amp`. I removed `&` from the password and corrected connection string in `Web.config` but there was obviously too late.

Now I recreated the enviroment from scratch and started converting. Console all the time is showing indicator with 'Working... Please wait.', database is not growing and `~/App_Data/Composite/Logfile` is clean. Could you help me again?

**Comment by Safety1st** [comment]
First time I used symbol `&` in password that was eventually escaped as `&amp`. I removed `&` from the password and corrected connection string in `Web.config` but there was obviously too late.

Now I recreated the enviroment from scratch and started converting. Console endlessly is showing indicator with 'Working... Please wait.', database is not growing and `~/App_Data/Composite/Logfile` is clean. Could you help me again?

**Comment by mawtex** [comment]
@Safety1st without any logs or errors, I can't pinpoint what the issue it. Did you follow the steps on https://c1.orckestra.com/Add-ons/All/Composite.Tools.SqlServerDataProvider/UserManual ?

**Comment by Safety1st** [comment]
There are no error logs. Things simply don't get changed xDD
Yes, I followed this simple guide and used such connection string: `Data Source=localhost;Initial Catalog=myDataBase;User Id=myUsername;Password=myPassword;`, and there is no problem with connection.

I wish to use C1 10 years and trying to install it from time to time without success. Why am I so unlucky that out-of-box software doesn't work for me?..

**Comment by mawtex** [comment]
> Why am I so unlucky that out-of-box software doesn't work for me?..

The web hosting need to offer asp.net in full trust mode and otherwise be standard, and all usually works smooth. If you are using local tools (WebMatrix, Visual Studio or pure IIS) or host on Azure Web Apps (basic or better), you should not experience this.

For the SQL migration, consider using the default XML provider - pushing data on to sql server only make sense if you have massive amount of data/content or intense data update frequency.

**Comment by Safety1st** [comment]
My hosting meet the mentioned requirement. I don’t want use local tools as well as other ‘working’ CMS. For Azure I don’t have 200$ for prepaid (free tier is expired).

Also I want to use database simply because it’s better any text based storage and it available.

Ok, I’ll ‘try’ your Community for helpness :)

**Comment by mawtex** [comment]
I'll mark the issue as resolved, sounds like the CSS part works for you now.
