### ISSUE TITLE
Creating new DataConnection results in a ObjectDisposedException

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#651]
I have a always-running background thread which once an hours does some house-cleaning involving creating a DataConnection.

Sometimes this results in the following exception and callstack and after alot of digging around the intricacy of DataConnection and ThreadDataManager my best guess is that there are some interlocks around multiple instatiated DataConnections where when one is being disposed triggering the disposal of the ThreadDataManager which results in a ObjectDisposedException the next time a DataConnection is being created !?

```
System.ObjectDisposedException: Cannot access a disposed object.Object name: 'TheadDataManagerData'.
   at Composite.Core.Threading.ThreadDataManagerData.CheckNotDisposed()
   at Composite.Core.Threading.ThreadDataManagerData.GetValue(Object key)
   at Composite.Core.ServiceLocator.get_RequestScopedServiceProvider()
   at Composite.Core.ServiceLocator.EnsureThreadDataServiceScope()
   at Composite.Core.Implementation.DataConnectionImplementation..ctor(PublicationScope scope, CultureInfo locale)
   at Composite.Core.Implementation.ImplementationFactory.CreateDataConnection(Nullable`1 scope, CultureInfo locale)
   at Composite.Data.DataConnection.<>c.<.ctor>b__5_0()
   at Composite.Core.Implementation.ImplementationContainer`1.CreateImplementation()
   at Composite.Data.DataConnection..ctor()
   at Hangfire.CompositeC1.CompositeC1Connection..ctor(TimeSpan queuePollInterval)
   at Hangfire.CompositeC1.CompositeC1Storage.GetConnection()
   at Hangfire.CompositeC1.ExpirationManager.Execute(CancellationToken cancellationToken)
   at Hangfire.CompositeC1.ExpirationManager.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

**Comment by burningice2866** [comment]
Please don't hesitate to ask for more information if needed.

**Comment by aeont** [comment]
same experience Build no. 6.5.6754.25114.

@burningice2866 it's might be related to scheduler... since it's always come with 
`Error occurred during execution of 'Hangfire.CompositeC1.ExpirationManager' process. Execution will be retried (attempt #20) in 00:05:00 seconds.`

**Comment by burningice2866** [comment]
The stacktrace looks pretty clear that the error happens when newing up a data connection like `new DataConnection()`. If that call can cause an exception we need to look at clarifying under what circumstance it isn't allowed to new up a data connection and what scenario can trigger this exception we're experiencing.

I've looked at the code for hours but i can't seem to figure out how the ThreadDataManagerData can't end up in a disposed state like this when newing up a data connection.
