### ISSUE TITLE
Virtual Path Maps to Another Application

### ISSUE THREAD

**Issue by rmzeck** [Orckestra/C1-CMS-Foundation#669]
I have a c1 website setup as application under a parent site: 

![2019-05-22_120806](https://user-images.githubusercontent.com/19580957/58191117-ef623580-7c8b-11e9-9737-b62aaafcf79f.png)

When configuring c1 this way in IIS, I'm noticing a fair amount of warnings in the site's log. Here's an example, and there are dozens more for other ashx and asmx files in the Renderers and Composite/services directories:
```
System.ArgumentException: The virtual path '/Renderers/TemplatePreview.ashx' maps to another application, which is not allowed.   at System.Web.VirtualPath.FailIfNotWithinAppRoot()
   at System.Web.Compilation.BuildManager.ValidateVirtualPathInternal(VirtualPath virtualPath, Boolean allowCrossApp, Boolean codeFile)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)

   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at Composite.Core.WebClient.BuildManagerHelper.LoadAllControls()
```
I haven't noticed any ill-effects of this, but I would like to clean up the log if possible. This issue doesn't occur when composite is setup directly at the website's root. I'm not certain if this is a bug, or if I'm doing something wrong with my configuration. 

Thanks for any advice!

Regards

**Comment by mawtex** [comment]
The warnings stem from a pre-compile process, which will compile file based asp.net handlers and controls in the background - for pre-compiling handlers this process didn't account for running in a virtual directory (using "/Composite/..." instead of "~/Composite/...").

There are functional ill-effects, worst case is a second or two delay in the first requests, hitting a handler that didn't get pre-compiled. But you do get a log full of useless noise, which is pretty terrible by itself, I will push in a fix.
