### ISSUE TITLE
Losing scheduled publication that has a start and end date

### ISSUE THREAD

**Issue by plouellet** [Orckestra/C1-CMS-Foundation#765]
I have an issue with scheduled publication in C1 with startdate and an end date. The creation works, but apparently, I keep losing the publication. 

I found a workaround, by not giving an enddate to the publication.

**Comment by burningice2866** [comment]
Are you saying that when the end date is reached, the content is simply removed from the system, instead of being unpublished and still accessible in the C1 Console?

**Comment by plouellet** [comment]
> 
> 
> Are you saying that when the end date is reached, the content is simply removed from the system, instead of being unpublished and still accessible in the C1 Console?

Yes, from my understanding this is exactly what's happening. 
Also, when I try to recreate a page with the same name as the "disappeared" one. I get this error : 

`InvalidOperationException:
Error executing workflow d5860b4b-8a04-452c-927d-221f03d50ec2

Stack trace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId)
   at Composite.C1Console.Workflow.WorkflowFlowController.OnFinish(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, FlowControllerServicesContainer formServicesContainer)
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.<>c__DisplayClass0_1.<Render>b__0(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)

InvalidOperationException:
Error executing workflow 2e524d37-3b48-49fe-b504-f9b3d3d7d456

Stack trace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId)
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(WorkflowInstance workflowInstance)
   at Composite.C1Console.Workflow.WorkflowActionExecutor.Execute(String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer)
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer, TaskManagerEvent taskManagerEvent)
   at Composite.Core.WebClient.FlowMediators.ActionExecutionService.Execute(EntityToken entityToken, ActionToken actionToken, TaskManagerEvent taskManagerEvent)
   at Composite.C1Console.Workflow.Activities.FormsWorkflow.ExecuteAction(EntityToken entityToken, ActionToken actionToken)
   at Orckestra.Versioning.VersionPublication.Workflow

NullReferenceException:
Object reference not set to an instance of an object.

Stack trace:
   at Composite.Plugins.Elements.ElementProviders.PageElementProvider.EditPageWorkflow.editStateCodeActivity_ExecuteCode(Object sender, EventArgs e)
   at System.Workflow.ComponentModel.Activity.RaiseEvent(DependencyProperty dependencyEvent, Object sender, EventArgs e)
   at System.Workflow.Activities.CodeActivity.Execute(ActivityExecutionContext executionContext)
   at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
   at System.Workflow.Runtime.Scheduler.Run()

Generated 2020-03-09 14:30

`
